// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EntTasksColumns holds the columns for the "ent_tasks" table.
	EntTasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "handler", Type: field.TypeString},
		{Name: "parameter", Type: field.TypeString},
		{Name: "priority", Type: field.TypeInt},
	}
	// EntTasksTable holds the schema information for the "ent_tasks" table.
	EntTasksTable = &schema.Table{
		Name:       "ent_tasks",
		Columns:    EntTasksColumns,
		PrimaryKey: []*schema.Column{EntTasksColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EntTasksTable,
	}
)

func init() {
}
