// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"fs.io/asyncd/ent/enttask"
	"fs.io/asyncd/ent/predicate"
)

// EntTaskQuery is the builder for querying EntTask entities.
type EntTaskQuery struct {
	config
	ctx        *QueryContext
	order      []enttask.OrderOption
	inters     []Interceptor
	predicates []predicate.EntTask
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*EntTask) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EntTaskQuery builder.
func (etq *EntTaskQuery) Where(ps ...predicate.EntTask) *EntTaskQuery {
	etq.predicates = append(etq.predicates, ps...)
	return etq
}

// Limit the number of records to be returned by this query.
func (etq *EntTaskQuery) Limit(limit int) *EntTaskQuery {
	etq.ctx.Limit = &limit
	return etq
}

// Offset to start from.
func (etq *EntTaskQuery) Offset(offset int) *EntTaskQuery {
	etq.ctx.Offset = &offset
	return etq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (etq *EntTaskQuery) Unique(unique bool) *EntTaskQuery {
	etq.ctx.Unique = &unique
	return etq
}

// Order specifies how the records should be ordered.
func (etq *EntTaskQuery) Order(o ...enttask.OrderOption) *EntTaskQuery {
	etq.order = append(etq.order, o...)
	return etq
}

// First returns the first EntTask entity from the query.
// Returns a *NotFoundError when no EntTask was found.
func (etq *EntTaskQuery) First(ctx context.Context) (*EntTask, error) {
	nodes, err := etq.Limit(1).All(setContextOp(ctx, etq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{enttask.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (etq *EntTaskQuery) FirstX(ctx context.Context) *EntTask {
	node, err := etq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EntTask ID from the query.
// Returns a *NotFoundError when no EntTask ID was found.
func (etq *EntTaskQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = etq.Limit(1).IDs(setContextOp(ctx, etq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{enttask.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (etq *EntTaskQuery) FirstIDX(ctx context.Context) int {
	id, err := etq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EntTask entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EntTask entity is found.
// Returns a *NotFoundError when no EntTask entities are found.
func (etq *EntTaskQuery) Only(ctx context.Context) (*EntTask, error) {
	nodes, err := etq.Limit(2).All(setContextOp(ctx, etq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{enttask.Label}
	default:
		return nil, &NotSingularError{enttask.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (etq *EntTaskQuery) OnlyX(ctx context.Context) *EntTask {
	node, err := etq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EntTask ID in the query.
// Returns a *NotSingularError when more than one EntTask ID is found.
// Returns a *NotFoundError when no entities are found.
func (etq *EntTaskQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = etq.Limit(2).IDs(setContextOp(ctx, etq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{enttask.Label}
	default:
		err = &NotSingularError{enttask.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (etq *EntTaskQuery) OnlyIDX(ctx context.Context) int {
	id, err := etq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EntTasks.
func (etq *EntTaskQuery) All(ctx context.Context) ([]*EntTask, error) {
	ctx = setContextOp(ctx, etq.ctx, ent.OpQueryAll)
	if err := etq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EntTask, *EntTaskQuery]()
	return withInterceptors[[]*EntTask](ctx, etq, qr, etq.inters)
}

// AllX is like All, but panics if an error occurs.
func (etq *EntTaskQuery) AllX(ctx context.Context) []*EntTask {
	nodes, err := etq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EntTask IDs.
func (etq *EntTaskQuery) IDs(ctx context.Context) (ids []int, err error) {
	if etq.ctx.Unique == nil && etq.path != nil {
		etq.Unique(true)
	}
	ctx = setContextOp(ctx, etq.ctx, ent.OpQueryIDs)
	if err = etq.Select(enttask.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (etq *EntTaskQuery) IDsX(ctx context.Context) []int {
	ids, err := etq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (etq *EntTaskQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, etq.ctx, ent.OpQueryCount)
	if err := etq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, etq, querierCount[*EntTaskQuery](), etq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (etq *EntTaskQuery) CountX(ctx context.Context) int {
	count, err := etq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (etq *EntTaskQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, etq.ctx, ent.OpQueryExist)
	switch _, err := etq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (etq *EntTaskQuery) ExistX(ctx context.Context) bool {
	exist, err := etq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EntTaskQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (etq *EntTaskQuery) Clone() *EntTaskQuery {
	if etq == nil {
		return nil
	}
	return &EntTaskQuery{
		config:     etq.config,
		ctx:        etq.ctx.Clone(),
		order:      append([]enttask.OrderOption{}, etq.order...),
		inters:     append([]Interceptor{}, etq.inters...),
		predicates: append([]predicate.EntTask{}, etq.predicates...),
		// clone intermediate query.
		sql:  etq.sql.Clone(),
		path: etq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Handler string `json:"handler,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EntTask.Query().
//		GroupBy(enttask.FieldHandler).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (etq *EntTaskQuery) GroupBy(field string, fields ...string) *EntTaskGroupBy {
	etq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EntTaskGroupBy{build: etq}
	grbuild.flds = &etq.ctx.Fields
	grbuild.label = enttask.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Handler string `json:"handler,omitempty"`
//	}
//
//	client.EntTask.Query().
//		Select(enttask.FieldHandler).
//		Scan(ctx, &v)
func (etq *EntTaskQuery) Select(fields ...string) *EntTaskSelect {
	etq.ctx.Fields = append(etq.ctx.Fields, fields...)
	sbuild := &EntTaskSelect{EntTaskQuery: etq}
	sbuild.label = enttask.Label
	sbuild.flds, sbuild.scan = &etq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EntTaskSelect configured with the given aggregations.
func (etq *EntTaskQuery) Aggregate(fns ...AggregateFunc) *EntTaskSelect {
	return etq.Select().Aggregate(fns...)
}

func (etq *EntTaskQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range etq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, etq); err != nil {
				return err
			}
		}
	}
	for _, f := range etq.ctx.Fields {
		if !enttask.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if etq.path != nil {
		prev, err := etq.path(ctx)
		if err != nil {
			return err
		}
		etq.sql = prev
	}
	return nil
}

func (etq *EntTaskQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EntTask, error) {
	var (
		nodes = []*EntTask{}
		_spec = etq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EntTask).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EntTask{config: etq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(etq.modifiers) > 0 {
		_spec.Modifiers = etq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, etq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	for i := range etq.loadTotal {
		if err := etq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (etq *EntTaskQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := etq.querySpec()
	if len(etq.modifiers) > 0 {
		_spec.Modifiers = etq.modifiers
	}
	_spec.Node.Columns = etq.ctx.Fields
	if len(etq.ctx.Fields) > 0 {
		_spec.Unique = etq.ctx.Unique != nil && *etq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, etq.driver, _spec)
}

func (etq *EntTaskQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(enttask.Table, enttask.Columns, sqlgraph.NewFieldSpec(enttask.FieldID, field.TypeInt))
	_spec.From = etq.sql
	if unique := etq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if etq.path != nil {
		_spec.Unique = true
	}
	if fields := etq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, enttask.FieldID)
		for i := range fields {
			if fields[i] != enttask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := etq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := etq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := etq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := etq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (etq *EntTaskQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(etq.driver.Dialect())
	t1 := builder.Table(enttask.Table)
	columns := etq.ctx.Fields
	if len(columns) == 0 {
		columns = enttask.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if etq.sql != nil {
		selector = etq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if etq.ctx.Unique != nil && *etq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range etq.predicates {
		p(selector)
	}
	for _, p := range etq.order {
		p(selector)
	}
	if offset := etq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := etq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EntTaskGroupBy is the group-by builder for EntTask entities.
type EntTaskGroupBy struct {
	selector
	build *EntTaskQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (etgb *EntTaskGroupBy) Aggregate(fns ...AggregateFunc) *EntTaskGroupBy {
	etgb.fns = append(etgb.fns, fns...)
	return etgb
}

// Scan applies the selector query and scans the result into the given value.
func (etgb *EntTaskGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, etgb.build.ctx, ent.OpQueryGroupBy)
	if err := etgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntTaskQuery, *EntTaskGroupBy](ctx, etgb.build, etgb, etgb.build.inters, v)
}

func (etgb *EntTaskGroupBy) sqlScan(ctx context.Context, root *EntTaskQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(etgb.fns))
	for _, fn := range etgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*etgb.flds)+len(etgb.fns))
		for _, f := range *etgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*etgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := etgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EntTaskSelect is the builder for selecting fields of EntTask entities.
type EntTaskSelect struct {
	*EntTaskQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ets *EntTaskSelect) Aggregate(fns ...AggregateFunc) *EntTaskSelect {
	ets.fns = append(ets.fns, fns...)
	return ets
}

// Scan applies the selector query and scans the result into the given value.
func (ets *EntTaskSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ets.ctx, ent.OpQuerySelect)
	if err := ets.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntTaskQuery, *EntTaskSelect](ctx, ets.EntTaskQuery, ets, ets.inters, v)
}

func (ets *EntTaskSelect) sqlScan(ctx context.Context, root *EntTaskQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ets.fns))
	for _, fn := range ets.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ets.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ets.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
