// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"fs.io/asyncd/ent/enttaskhandler"
	"fs.io/asyncd/ent/predicate"
)

// EntTaskHandlerQuery is the builder for querying EntTaskHandler entities.
type EntTaskHandlerQuery struct {
	config
	ctx        *QueryContext
	order      []enttaskhandler.OrderOption
	inters     []Interceptor
	predicates []predicate.EntTaskHandler
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*EntTaskHandler) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EntTaskHandlerQuery builder.
func (ethq *EntTaskHandlerQuery) Where(ps ...predicate.EntTaskHandler) *EntTaskHandlerQuery {
	ethq.predicates = append(ethq.predicates, ps...)
	return ethq
}

// Limit the number of records to be returned by this query.
func (ethq *EntTaskHandlerQuery) Limit(limit int) *EntTaskHandlerQuery {
	ethq.ctx.Limit = &limit
	return ethq
}

// Offset to start from.
func (ethq *EntTaskHandlerQuery) Offset(offset int) *EntTaskHandlerQuery {
	ethq.ctx.Offset = &offset
	return ethq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ethq *EntTaskHandlerQuery) Unique(unique bool) *EntTaskHandlerQuery {
	ethq.ctx.Unique = &unique
	return ethq
}

// Order specifies how the records should be ordered.
func (ethq *EntTaskHandlerQuery) Order(o ...enttaskhandler.OrderOption) *EntTaskHandlerQuery {
	ethq.order = append(ethq.order, o...)
	return ethq
}

// First returns the first EntTaskHandler entity from the query.
// Returns a *NotFoundError when no EntTaskHandler was found.
func (ethq *EntTaskHandlerQuery) First(ctx context.Context) (*EntTaskHandler, error) {
	nodes, err := ethq.Limit(1).All(setContextOp(ctx, ethq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{enttaskhandler.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ethq *EntTaskHandlerQuery) FirstX(ctx context.Context) *EntTaskHandler {
	node, err := ethq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EntTaskHandler ID from the query.
// Returns a *NotFoundError when no EntTaskHandler ID was found.
func (ethq *EntTaskHandlerQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ethq.Limit(1).IDs(setContextOp(ctx, ethq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{enttaskhandler.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ethq *EntTaskHandlerQuery) FirstIDX(ctx context.Context) int {
	id, err := ethq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EntTaskHandler entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EntTaskHandler entity is found.
// Returns a *NotFoundError when no EntTaskHandler entities are found.
func (ethq *EntTaskHandlerQuery) Only(ctx context.Context) (*EntTaskHandler, error) {
	nodes, err := ethq.Limit(2).All(setContextOp(ctx, ethq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{enttaskhandler.Label}
	default:
		return nil, &NotSingularError{enttaskhandler.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ethq *EntTaskHandlerQuery) OnlyX(ctx context.Context) *EntTaskHandler {
	node, err := ethq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EntTaskHandler ID in the query.
// Returns a *NotSingularError when more than one EntTaskHandler ID is found.
// Returns a *NotFoundError when no entities are found.
func (ethq *EntTaskHandlerQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ethq.Limit(2).IDs(setContextOp(ctx, ethq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{enttaskhandler.Label}
	default:
		err = &NotSingularError{enttaskhandler.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ethq *EntTaskHandlerQuery) OnlyIDX(ctx context.Context) int {
	id, err := ethq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EntTaskHandlers.
func (ethq *EntTaskHandlerQuery) All(ctx context.Context) ([]*EntTaskHandler, error) {
	ctx = setContextOp(ctx, ethq.ctx, ent.OpQueryAll)
	if err := ethq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EntTaskHandler, *EntTaskHandlerQuery]()
	return withInterceptors[[]*EntTaskHandler](ctx, ethq, qr, ethq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ethq *EntTaskHandlerQuery) AllX(ctx context.Context) []*EntTaskHandler {
	nodes, err := ethq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EntTaskHandler IDs.
func (ethq *EntTaskHandlerQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ethq.ctx.Unique == nil && ethq.path != nil {
		ethq.Unique(true)
	}
	ctx = setContextOp(ctx, ethq.ctx, ent.OpQueryIDs)
	if err = ethq.Select(enttaskhandler.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ethq *EntTaskHandlerQuery) IDsX(ctx context.Context) []int {
	ids, err := ethq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ethq *EntTaskHandlerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ethq.ctx, ent.OpQueryCount)
	if err := ethq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ethq, querierCount[*EntTaskHandlerQuery](), ethq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ethq *EntTaskHandlerQuery) CountX(ctx context.Context) int {
	count, err := ethq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ethq *EntTaskHandlerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ethq.ctx, ent.OpQueryExist)
	switch _, err := ethq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ethq *EntTaskHandlerQuery) ExistX(ctx context.Context) bool {
	exist, err := ethq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EntTaskHandlerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ethq *EntTaskHandlerQuery) Clone() *EntTaskHandlerQuery {
	if ethq == nil {
		return nil
	}
	return &EntTaskHandlerQuery{
		config:     ethq.config,
		ctx:        ethq.ctx.Clone(),
		order:      append([]enttaskhandler.OrderOption{}, ethq.order...),
		inters:     append([]Interceptor{}, ethq.inters...),
		predicates: append([]predicate.EntTaskHandler{}, ethq.predicates...),
		// clone intermediate query.
		sql:  ethq.sql.Clone(),
		path: ethq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EntTaskHandler.Query().
//		GroupBy(enttaskhandler.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ethq *EntTaskHandlerQuery) GroupBy(field string, fields ...string) *EntTaskHandlerGroupBy {
	ethq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EntTaskHandlerGroupBy{build: ethq}
	grbuild.flds = &ethq.ctx.Fields
	grbuild.label = enttaskhandler.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.EntTaskHandler.Query().
//		Select(enttaskhandler.FieldName).
//		Scan(ctx, &v)
func (ethq *EntTaskHandlerQuery) Select(fields ...string) *EntTaskHandlerSelect {
	ethq.ctx.Fields = append(ethq.ctx.Fields, fields...)
	sbuild := &EntTaskHandlerSelect{EntTaskHandlerQuery: ethq}
	sbuild.label = enttaskhandler.Label
	sbuild.flds, sbuild.scan = &ethq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EntTaskHandlerSelect configured with the given aggregations.
func (ethq *EntTaskHandlerQuery) Aggregate(fns ...AggregateFunc) *EntTaskHandlerSelect {
	return ethq.Select().Aggregate(fns...)
}

func (ethq *EntTaskHandlerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ethq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ethq); err != nil {
				return err
			}
		}
	}
	for _, f := range ethq.ctx.Fields {
		if !enttaskhandler.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ethq.path != nil {
		prev, err := ethq.path(ctx)
		if err != nil {
			return err
		}
		ethq.sql = prev
	}
	return nil
}

func (ethq *EntTaskHandlerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EntTaskHandler, error) {
	var (
		nodes = []*EntTaskHandler{}
		_spec = ethq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EntTaskHandler).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EntTaskHandler{config: ethq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(ethq.modifiers) > 0 {
		_spec.Modifiers = ethq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ethq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	for i := range ethq.loadTotal {
		if err := ethq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ethq *EntTaskHandlerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ethq.querySpec()
	if len(ethq.modifiers) > 0 {
		_spec.Modifiers = ethq.modifiers
	}
	_spec.Node.Columns = ethq.ctx.Fields
	if len(ethq.ctx.Fields) > 0 {
		_spec.Unique = ethq.ctx.Unique != nil && *ethq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ethq.driver, _spec)
}

func (ethq *EntTaskHandlerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(enttaskhandler.Table, enttaskhandler.Columns, sqlgraph.NewFieldSpec(enttaskhandler.FieldID, field.TypeInt))
	_spec.From = ethq.sql
	if unique := ethq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ethq.path != nil {
		_spec.Unique = true
	}
	if fields := ethq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, enttaskhandler.FieldID)
		for i := range fields {
			if fields[i] != enttaskhandler.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ethq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ethq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ethq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ethq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ethq *EntTaskHandlerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ethq.driver.Dialect())
	t1 := builder.Table(enttaskhandler.Table)
	columns := ethq.ctx.Fields
	if len(columns) == 0 {
		columns = enttaskhandler.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ethq.sql != nil {
		selector = ethq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ethq.ctx.Unique != nil && *ethq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ethq.predicates {
		p(selector)
	}
	for _, p := range ethq.order {
		p(selector)
	}
	if offset := ethq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ethq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EntTaskHandlerGroupBy is the group-by builder for EntTaskHandler entities.
type EntTaskHandlerGroupBy struct {
	selector
	build *EntTaskHandlerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ethgb *EntTaskHandlerGroupBy) Aggregate(fns ...AggregateFunc) *EntTaskHandlerGroupBy {
	ethgb.fns = append(ethgb.fns, fns...)
	return ethgb
}

// Scan applies the selector query and scans the result into the given value.
func (ethgb *EntTaskHandlerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ethgb.build.ctx, ent.OpQueryGroupBy)
	if err := ethgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntTaskHandlerQuery, *EntTaskHandlerGroupBy](ctx, ethgb.build, ethgb, ethgb.build.inters, v)
}

func (ethgb *EntTaskHandlerGroupBy) sqlScan(ctx context.Context, root *EntTaskHandlerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ethgb.fns))
	for _, fn := range ethgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ethgb.flds)+len(ethgb.fns))
		for _, f := range *ethgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ethgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ethgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EntTaskHandlerSelect is the builder for selecting fields of EntTaskHandler entities.
type EntTaskHandlerSelect struct {
	*EntTaskHandlerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (eths *EntTaskHandlerSelect) Aggregate(fns ...AggregateFunc) *EntTaskHandlerSelect {
	eths.fns = append(eths.fns, fns...)
	return eths
}

// Scan applies the selector query and scans the result into the given value.
func (eths *EntTaskHandlerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eths.ctx, ent.OpQuerySelect)
	if err := eths.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntTaskHandlerQuery, *EntTaskHandlerSelect](ctx, eths.EntTaskHandlerQuery, eths, eths.inters, v)
}

func (eths *EntTaskHandlerSelect) sqlScan(ctx context.Context, root *EntTaskHandlerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(eths.fns))
	for _, fn := range eths.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*eths.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eths.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
