// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"fs.io/asyncd/ent/enttask"
	"fs.io/asyncd/ent/predicate"
)

// EntTaskDelete is the builder for deleting a EntTask entity.
type EntTaskDelete struct {
	config
	hooks    []Hook
	mutation *EntTaskMutation
}

// Where appends a list predicates to the EntTaskDelete builder.
func (etd *EntTaskDelete) Where(ps ...predicate.EntTask) *EntTaskDelete {
	etd.mutation.Where(ps...)
	return etd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (etd *EntTaskDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, etd.sqlExec, etd.mutation, etd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (etd *EntTaskDelete) ExecX(ctx context.Context) int {
	n, err := etd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (etd *EntTaskDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(enttask.Table, sqlgraph.NewFieldSpec(enttask.FieldID, field.TypeInt))
	if ps := etd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, etd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	etd.mutation.done = true
	return affected, err
}

// EntTaskDeleteOne is the builder for deleting a single EntTask entity.
type EntTaskDeleteOne struct {
	etd *EntTaskDelete
}

// Where appends a list predicates to the EntTaskDelete builder.
func (etdo *EntTaskDeleteOne) Where(ps ...predicate.EntTask) *EntTaskDeleteOne {
	etdo.etd.mutation.Where(ps...)
	return etdo
}

// Exec executes the deletion query.
func (etdo *EntTaskDeleteOne) Exec(ctx context.Context) error {
	n, err := etdo.etd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{enttask.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (etdo *EntTaskDeleteOne) ExecX(ctx context.Context) {
	if err := etdo.Exec(ctx); err != nil {
		panic(err)
	}
}
