// Code generated by ent, DO NOT EDIT.

package ent

// CreateEntTaskInput represents a mutation input for creating enttasks.
type CreateEntTaskInput struct {
	Handler   string
	Parameter string
	Priority  int
}

// Mutate applies the CreateEntTaskInput on the EntTaskMutation builder.
func (i *CreateEntTaskInput) Mutate(m *EntTaskMutation) {
	m.SetHandler(i.Handler)
	m.SetParameter(i.Parameter)
	m.SetPriority(i.Priority)
}

// SetInput applies the change-set in the CreateEntTaskInput on the EntTaskCreate builder.
func (c *EntTaskCreate) SetInput(i CreateEntTaskInput) *EntTaskCreate {
	i.Mutate(c.Mutation())
	return c
}
