// Code generated by ent, DO NOT EDIT.

package enttask

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the enttask type in the database.
	Label = "ent_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHandler holds the string denoting the handler field in the database.
	FieldHandler = "handler"
	// FieldParameter holds the string denoting the parameter field in the database.
	FieldParameter = "parameter"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// Table holds the table name of the enttask in the database.
	Table = "ent_tasks"
)

// Columns holds all SQL columns for enttask fields.
var Columns = []string{
	FieldID,
	FieldHandler,
	FieldParameter,
	FieldPriority,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the EntTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHandler orders the results by the handler field.
func ByHandler(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHandler, opts...).ToFunc()
}

// ByParameter orders the results by the parameter field.
func ByParameter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParameter, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}
