// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// EntTask is the predicate function for enttask builders.
type EntTask func(*sql.Selector)

// EntTaskHandler is the predicate function for enttaskhandler builders.
type EntTaskHandler func(*sql.Selector)
